version: '3.4'

networks:
  expensesapp:
  
services:
  expensesdbdemo:
    container_name: demo-expenses-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=pass
      - MSSQL_PID=Developer
    ports:
      - "1433:1433" 
    volumes:
      - mssql_data:/var/opt/mssql
    user: root
    networks:
      - expensesapp

  expensesapi:
    container_name: demo-expenses-api
    image: ${DOCKER_REGISTRY-}expenses-api
    build:
      context: ./ExpensesApi
      dockerfile: ./Dockerfile
    ports:
      - "5600:80"
      - "5800:443"
    depends_on:
      - expensesdbdemo
    environment:
      - ConnectionStrings__ExpenseDbString=Data Source=expensesdbdemo; Initial Catalog=ExpenseDb; Persist Security Info=True;User ID=sa;Password=pass
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_URLS=https://+:443;http://+:80
    networks:
      - expensesapp
    
  documentapi:
    container_name: demo-document-api
    image: ${DOCKER_REGISTRY-}document-api
    build:
      context: ./DocumentApi/DocumentApi
      dockerfile: ./Dockerfile
    ports:
      - "5650:90"
      - "5850:450"
    networks:
      - expensesapp

  angular:
    image: ui-test-angular
    container_name: demo-expenses-angular
    build:
      context: ./expenses-api
      dockerfile: ./Dockerfile
    ports:
      - 4200:80
    networks:
      - expensesapp

volumes:
  mssql_data: