// <auto-generated />
using System;
using DatabaseProj.DatabaseEntities.ConnectionInfo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseProj.Migrations
{
    [DbContext(typeof(ExpensesApiDb))]
    [Migration("20220927162548_fix")]
    partial class fix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DatabaseProj.Database.Models.UserExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserExpensesListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserExpensesListId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("DatabaseProj.DatabaseEntities.Models.UserExpenseGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MonthChosenForGoal")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserExpensesListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserExpensesListId");

                    b.ToTable("UserExpensesGoals");
                });

            modelBuilder.Entity("DatabaseProj.DatabaseEntities.Models.UserExpensesList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ExpensesLists");
                });

            modelBuilder.Entity("DatabaseProj.DatabaseEntities.Models.UserGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<decimal>("Limit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserExpenseGoalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserExpenseGoalId");

                    b.ToTable("UserGoals");
                });

            modelBuilder.Entity("DatabaseProj.DatabaseEntities.Models.UserIncome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Income")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserExpensesListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserExpensesListId");

                    b.ToTable("UserIncomes");
                });

            modelBuilder.Entity("DatabaseProj.Database.Models.UserExpense", b =>
                {
                    b.HasOne("DatabaseProj.DatabaseEntities.Models.UserExpensesList", "UserExpensesList")
                        .WithMany("Expenses")
                        .HasForeignKey("UserExpensesListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserExpensesList");
                });

            modelBuilder.Entity("DatabaseProj.DatabaseEntities.Models.UserExpenseGoal", b =>
                {
                    b.HasOne("DatabaseProj.DatabaseEntities.Models.UserExpensesList", "UserExpensesList")
                        .WithMany("UserGoals")
                        .HasForeignKey("UserExpensesListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserExpensesList");
                });

            modelBuilder.Entity("DatabaseProj.DatabaseEntities.Models.UserGoal", b =>
                {
                    b.HasOne("DatabaseProj.DatabaseEntities.Models.UserExpenseGoal", "UserExpenseGoal")
                        .WithMany("UserCategoryGoals")
                        .HasForeignKey("UserExpenseGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserExpenseGoal");
                });

            modelBuilder.Entity("DatabaseProj.DatabaseEntities.Models.UserIncome", b =>
                {
                    b.HasOne("DatabaseProj.DatabaseEntities.Models.UserExpensesList", "UserExpensesList")
                        .WithMany("UserIncome")
                        .HasForeignKey("UserExpensesListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserExpensesList");
                });

            modelBuilder.Entity("DatabaseProj.DatabaseEntities.Models.UserExpenseGoal", b =>
                {
                    b.Navigation("UserCategoryGoals");
                });

            modelBuilder.Entity("DatabaseProj.DatabaseEntities.Models.UserExpensesList", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("UserGoals");

                    b.Navigation("UserIncome");
                });
#pragma warning restore 612, 618
        }
    }
}
